Translate upgrade document to Korean
kosslab-kr/zeppelin pull request #8
Opened 2016-09-28 12:18 UTC by gaonnuryhj

### What is this PR for?
 More people can understand that how to upgrade the Zeppelin.

### What type of PR is it?
[Documentation]

### Todos
Translate upgrade document to Korean.

### What is the Jira issue?

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

2016-09-28 12:42 UTC, yoonjs2 requested changes
보내주신 내용을 리뷰해 보았습니다. 확인 부탁드리며 다음부터 업로드 하시기 전에 한글 문법검사 한번만 부탁드리겠습니다.

2016-09-28 12:42 UTC, yoonjs2 commented on docs/install/upgrade.md
> +기본적으로 새로운 버전의 제플린은 이전 버전의 환경설정과 notebook 폴더와 호환이 됩니다. 그러므로 'notebook'과 'conf' 폴더를 가능하다면 복사해두는 것이 좋습니다.
오역이 있는것 같습니다. ```그러므로 'notebook'과 'conf' 폴더를 가능하다면 복사해두는 것이 좋습니다.``` -> ```그러므로 이전 버전의 'notebook'과 'conf' 폴더를 새 버전에 복사해 두는걸로 충분합니다.```로 바꿔야 할것 같습니다. 앞 문장이 notebook 폴더와 설정이 이전 또는 이후 버전과 호환된다는 내용이기 때문에 이렇게 해야 의미가 좀더 분명할것 같습니다.

2016-09-28 12:42 UTC, yoonjs2 commented on docs/install/upgrade.md
> +1. 제플린의 실행은 중지시킵니다.
맨 아래 문장과의 일치성을 위해서 이렇게 문장을 고쳐두는게 좀더 나을것 같습니다. ```제플린의 실행은 중지시킵니다.```->```제플린을 종료시킵니다.```

2016-09-28 12:42 UTC, yoonjs2 commented on docs/install/upgrade.md
> +3. 새로운 버전의 제플린을 다운로드 받고 설치합니다. 참고 : [다운 받을 수 있는 페이지](./install.html#installation).
```참고 : [다운 받을 수 있는 페이지]```->```참고: [설치 가이드]```

2016-09-28 12:42 UTC, yoonjs2 commented on docs/install/upgrade.md
```백업 폴더의 `notebook` 과 `conf`폴더를 새로운 버전의 제플린의 `notebook` and `conf`로 붙여넣기 합니다.```->```백업해둔 `notebook` 과 `conf`폴더를 새로운 버전의 제플린의 `notebook` 과 `conf`폴더에 붙여넣기 합니다.```

2016-09-28 12:42 UTC, yoonjs2 commented on docs/install/upgrade.md
> +## 참고 사항
```참고 사항```->```마이그레이션 시 참고사항```

2016-09-29 01:12 UTC, gaonnuryhj commented on docs/install/upgrade.md
> +기본적으로 새로운 버전의 제플린은 이전 버전의 환경설정과 notebook 폴더와 호환이 됩니다. 그러므로 'notebook'과 'conf' 폴더를 가능하다면 복사해두는 것이 좋습니다.
수정했습니다!!

2016-09-29 01:12 UTC, gaonnuryhj commented on docs/install/upgrade.md
> +1. 제플린의 실행은 중지시킵니다.
수정했습니다.

2016-09-29 01:13 UTC, gaonnuryhj commented on docs/install/upgrade.md
> +3. 새로운 버전의 제플린을 다운로드 받고 설치합니다. 참고 : [다운 받을 수 있는 페이지](./install.html#installation).
수정했습니다.

2016-09-29 01:13 UTC, gaonnuryhj commented on docs/install/upgrade.md
수정했습니다.

2016-09-29 01:13 UTC, gaonnuryhj commented on docs/install/upgrade.md
> +## 참고 사항
수정했습니다.

2016-09-29 13:25 UTC, gaonnuryhj commented
dynamicform.md 파일 추가되었습니다.

2016-09-29 14:22 UTC, gaonnuryhj commented
publish.md 파일 추가하였습니다.

2016-09-30 10:21 UTC, yoonjs2 approved these changes

2016-09-30 10:33 UTC, yoonjs2 approved these changes
저번보다 더 좋은 퀄리티로 번역해 주셨네요! 감사합니다! 초깃값이 표준어인지 저도 처음 알았네요 :)

2016-09-30 10:33 UTC, merged